### ISSUE TITLE
Suspending when steam deck is on 20% or 22% but plugged in!

### ISSUE THREAD

**Issue by dgpmaluco** [jurassicplayer/decky-autosuspend#4] opened 2023-01-20 16:38 UTC
Hello,

Having a problem where the plug-in warns me of critical level and suspends the steam deck when it’s around 20% but loading with the original charger!

Warning level is set at 20% and Critical Level at 10%.

Reloding the plug-in or resaving the values doesn’t help.

**Comment by jurassicplayer** [comment] 2023-01-20 19:10
Could you provide the following information:
 - decky-loader verison
 - SteamOS update channel (Stable, Beta, Preview)
 - AutoSuspend verison

And the following files (grab these before hard restarting):
 - `journalctl -eu plugin_loader.service > decky-loader.log`
 - `/tmp/autosuspend.log`

Are you able to reproduce the issue after a restart and can you provide the steps you took to cause the issue?

**Comment by dgpmaluco** [comment] 2023-01-21 20:53
Decky Loader: 2.5.0-pre1
SteamOS: Stable
AutoSuspend: 1.2.1

I was able to reproduce it. Shutdown the steam deck. Charged it fully, played until reaching 21% plugged it in and immediately the warning came and suspended the SteamDeck

**Comment by dgpmaluco** [comment] 2023-01-21 21:00
https://pastebin.com/tDL0rjAM     autosuspend.log
https://pastebin.com/AEp3XBjb     decky-loader.log

**Comment by jurassicplayer** [comment] 2023-01-23 10:13
Can you check to see if you can replicate the issue on the latest version of AutoSuspend (v1.3.4)? It should be available in the testing store. Just make sure you do a full `Restart` and not the `Restart Steam` after updating.

If possible, if you could also turn on `Allow Remote CEF Debugging` and using a computer on the same network as your device, navigate (using a chromium-based browser) to: `http://<your-device-ip>:8081`, click on the link that says `Steam`, and then get a copy of the `Console` log after testing, that would be great.
e.g. (Make sure the level is set to `All levels`): ![example](https://i.imgur.com/1jzsSEG.png)

**Comment by dgpmaluco** [comment] 2023-01-24 20:43
So I updated to the tets branch and updated at the same time decky to version v2.5.1 and it’s currently not happening. Do you still need any logs or the cef debugging?

**Comment by jurassicplayer** [comment] 2023-01-24 21:30
If the updated version works for you, then you don't need to send the logs. It may have been a bug I fixed during [one of the updates](https://github.com/jurassicplayer/decky-autosuspend/issues/1#issuecomment-1363798716) from v1.2.1

It's not recommended to use plugins from the testing store since they are...well, in testing by other users...so you should at least make sure that you change your decky store channel back to default. Decky-loader will nag you about there being an updated version of AutoSuspend if you leave the testing store version installed (decky-loader doesn't check the version, just that it's different), but if that doesn't bother you, you can leave it. Otherwise, you can downgrade AutoSuspend and just wait for the version to be released in the default store.

If you come across the issue again, feel free to re-open, but for now I'm going to close the issue as it seems to have been resolved.

**Closed by jurassicplayer** 2023-01-24 21:30 UTC
